{
 "title": "Hystrix Dashboard",
 "description": "Dashboard to monitor key metrics for Hystrix. The Hystrix metrics are published using Prometheus' simpleclient through this library https://github.com/soundcloud/prometheus-hystrix",
 "time": { "from": "2018-04-24T03:43:40.073Z", "to": "2018-04-24T09:43:40.073Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(job)" },
   {
    "name": "commandGroup",
    "label": "Command Group",
    "query": "query_result({job=~\"$service\"})"
   },
   {
    "name": "commandName",
    "label": "Command Name",
    "query": "query_result({job=~\"$service\",command_group=~\"$commandGroup\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Status",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum({__name__=~\".*_hystrix_command_is_circuit_breaker_open\",command_group=~\"$commandGroup\",command_name=~\"$commandName\"})== bool 0 and sum({__name__=~\".*_hystrix_command_rolling_count_exceptions_thrown\",command_group=~\"$commandGroup\",command_name=~\"$commandName\"}) == bool 0"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum({__name__=~\".*_hystrix_command_error_percentage\",command_group=~\"$commandGroup\",command_name=~\"$commandName\",job=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Mean Latency",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_command_latency_total_mean\",command_group=~\"$commandGroup\",command_name=~\"$commandName\",job=~\"$service\"}",
     "legendFormat": "{{command_name}} ({{command_group}})"
    }
   ]
  },
  {
   "title": "Total Latency (90th)",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_command_latency_total_percentile_90\",command_group=~\"$commandGroup\",command_name=~\"$commandName\",job=~\"$service\"}",
     "legendFormat": "{{command_name}} ({{command_group}})"
    }
   ]
  },
  {
   "title": "Total Latency (99th)",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_command_latency_total_percentile_99\",command_group=~\"$commandGroup\",command_name=~\"$commandName\",job=~\"$service\"}",
     "legendFormat": "{{command_name}} ({{command_group}})"
    }
   ]
  },
  {
   "title": "Total Latency (99.5th)",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_command_latency_total_percentile_995\",command_group=~\"$commandGroup\",command_name=~\"$commandName\",job=~\"$service\"}",
     "legendFormat": "{{command_name}} ({{command_group}})"
    }
   ]
  },
  {
   "title": "Open Circuit Breakers Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_command_is_circuit_breaker_open\",command_group=~\"$commandGroup\",job=~\"$service\"}",
     "legendFormat": "{{command_name}} ({{command_group}})"
    }
   ]
  },
  {
   "title": "Command Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*hystrix_command_error_total\",command_group=~\"$commandGroup\",job=~\"$service\"}",
     "legendFormat": "{{command_name}} ({{command_group}})"
    }
   ]
  },
  {
   "title": "Command Successes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_command_count_success\",command_group=~\"$commandGroup\",job=~\"$service\"}",
     "legendFormat": "{{command_name}} ({{command_group}})"
    }
   ]
  },
  {
   "title": "Command Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_command_count_timeout\",command_group=~\"$commandGroup\",command_name=~\"$commandName\",job=~\"$service\"}",
     "legendFormat": "{{command_name}} ({{command_group}})"
    }
   ]
  },
  {
   "title": "Thread Pool / Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_thread_pool_queue_size\", pool_name=~\"$commandGroup\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Thread Pool / Active Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_thread_pool_thread_active_count\", pool_name=~\"$commandGroup\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Thread Pool / Completed Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_thread_pool_completed_task_count\", pool_name=~\"$commandGroup\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Thread Pool / Rejected Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_hystrix_thread_pool_thread_pool_rejected\", pool_name=~\"$commandGroup\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  }
 ]
}